# Generated by Django 4.1.3 on 2023-11-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_ticket_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Festa', 'Festa')], max_length=40, unique=True),
        ),
    ]
