# Generated by Django 4.1.3 on 2023-11-27 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_alter_category_id_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='organizer',
            new_name='staff',
        ),
    ]
